version: "3.8"

services:
  web:
    image: sahithy/facts
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: go run ./cmd/main.go -b 0.0.0.0
    depends_on:
      - db
      - pulsar
    networks:
      - app-network

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - app-network

  pulsar:
    image: apachepulsar/pulsar:latest
    ports:
      - "6650:6650"
      - "8080:8080"
    command: ["bin/pulsar", "standalone"]
    networks:
      - app-network

networks:
  app-network:
