apiVersion: v1
kind: Service
metadata:
  name: pulsar
spec:
  ports:
    - port: 6650
      targetPort: 6650
      name: pulsar
    - port: 8080
      targetPort: 8080
      name: pulsar-admin
  selector:
    app: pulsar
