apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulsar-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pulsar
  template:
    metadata:
      labels:
        app: pulsar
    spec:
      containers:
        - name: pulsar
          image: apachepulsar/pulsar:latest
          command: ["bin/pulsar", "standalone"]
          ports:
            - containerPort: 6650
            - containerPort: 8080
